import typing

import enum

from . import types
from ..syntax.typethon import ast


class ContextFlags(enum.IntFlag):
    NONE = 0
    ALLOW_RETURN = enum.auto()
    ALLOW_LOOP_CONTROL = enum.auto()


class AnalysisContext:
    # TODO: Update function signatures, not everything will have a specific type.
    # Preserve symbols for name hooks, preserve scopes for functions/classes?
    # We must be able to create an abstract syntax graph using this class.
    def __init__(self, outer_type: typing.Optional[types.AnalyzedType] = None) -> None:
        self.outer_type = outer_type
        self.flags = ContextFlags.NONE

    def create_inner_context(self, outer_type: types.AnalyzedType) -> typing.Self:
        cls = type(self)
        return cls(outer_type)

    def bool_op_hook(self, type: types.AnalysisUnit, node: ast.BoolOpNode) -> None: ...

    def binary_op_hook(self, type: types.AnalysisUnit, node: ast.BinaryOpNode) -> None: ...

    def unary_op_hook(self, type: types.AnalysisUnit, node: ast.UnaryOpNode) -> None: ...

    def dict_hook(self, type: types.AnalysisUnit, node: ast.DictNode) -> None: ...

    def set_hook(self, type: types.AnalysisUnit, node: ast.SetNode) -> None: ...

    def compare_hook(self, type: types.AnalysisUnit, node: ast.CompareNode) -> None: ...

    def call_hook(self, type: types.AnalysisUnit, node: ast.CallNode) -> None: ...

    def formatted_value_hook(self, type: types.AnalysisUnit, node: ast.FormattedValueNode) -> None: ...

    def constant_hook(self, type: types.AnalysisUnit, node: ast.ConstantNode) -> None: ...

    def attribute_hook(self, type: types.AnalysisUnit, node: ast.AttributeNode) -> None: ...

    def subscript_hook(self, type: types.AnalysisUnit, node: ast.SubscriptNode) -> None: ...

    def name_hook(self, type: types.AnalysisUnit, node: ast.NameNode) -> None: ...

    def list_hook(self, type: types.AnalysisUnit, node: ast.ListNode) -> None: ...

    def tuple_hook(self, type: types.AnalysisUnit, node: ast.TupleNode) -> None: ...

    def slice_hook(self, type: types.AnalysisUnit, node: ast.SliceNode) -> None: ...    

    def function_def_hook(self, type: types.AnalysisUnit, node: ast.FunctionDefNode) -> None: ...

    def class_def_hook(self, type: types.AnalysisUnit, node: ast.ClassDefNode) -> None: ...

    def return_hook(self, type: types.AnalysisUnit, node: ast.ReturnNode) -> None: ...

    def delete_hook(self, type: types.AnalysisUnit, node: ast.DeleteNode) -> None: ...

    def assign_hook(self, type: types.AnalysisUnit, node: ast.AssignNode) -> None: ...

    def aug_assign_hook(self, type: types.AnalysisUnit, node: ast.AugAssignNode) -> None: ...

    def ann_assign_hook(self, type: types.AnalysisUnit, node: ast.AnnAssignNode) -> None: ...

    def for_hook(self, type: types.AnalysisUnit, node: ast.ForNode) -> None: ...

    def while_hook(self, type: types.AnalysisUnit, node: ast.WhileNode) -> None: ...

    def if_hook(self, type: types.AnalysisUnit, node: ast.IfNode) -> None: ...

    def import_hook(self, type: types.AnalysisUnit, node: ast.ImportNode) -> None: ...

    def import_from_hook(self, type: types.AnalysisUnit, node: ast.ImportFromNode) -> None: ...

    def expr_hook(self, type: types.AnalysisUnit, node: ast.ExprNode) -> None: ...

    def pass_hook(self, node: ast.PassNode) -> None: ...

    def break_hook(self, node: ast.BreakNode) -> None: ...

    def continue_hook(self, node: ast.ContinueNode) -> None: ...
